# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='UserIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True, unpack_ipv4=True)),
            ],
        ),
        migrations.AddField(
            model_name='mymodel',
            name='userip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpdview.UserIP'),
        ),
    ]
